"""Generates docs/builtins.md from the list of builtin functions."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from jarlang.builtins import BUILTINS, CONSTANT_DOCS, CONSTANTS  # noqa: E402
from jarlang.native.typecheck import NATIVE_BUILTINS  # noqa: E402
from jarlang.values import Builtin  # noqa: E402

CATEGORY_TITLES = {
    "io": "Input and Output",
    "math": "Math",
    "stats": "Statistics",
    "list": "Lists",
    "functional": "Functions",
    "string": "Strings",
    "dict": "Dicts",
    "convert": "Conversions",
    "random": "Random Numbers",
    "misc": "Other",
}


def render() -> str:
    by_cat: dict[str, list[Builtin]] = {}
    for b in BUILTINS.values():
        if isinstance(b, Builtin):
            by_cat.setdefault(b.category, []).append(b)
    total = sum(len(v) for v in by_cat.values())
    out = [
        "# Built-in Functions",
        "",
        "<!-- Generated by tools/gen_builtins_doc.py -->",
        "",
        f"JarLang has {total} built-in functions. Functions marked with (native) also work with the native "
        "compiler.",
        "",
        "Functions that take a list take it as the first argument, so `xs.map(f)` and `xs |> map(f)` are the "
        "same as `map(xs, f)`.",
        "",
        "### Constants",
        "",
    ]
    seen = set()
    for name, value in CONSTANTS.items():
        if value in seen and name in ("π", "τ", "φ"):
            continue
        seen.add(value)
        alias = {"pi": " (or `π`)", "tau": " (or `τ`)", "phi": " (or `φ`)", "inf": " (or `∞`)"}.get(name, "")
        out.append(f"* `{name}`{alias}: {CONSTANT_DOCS.get(name, repr(value))}")
    out.append("")
    order = ["io", "math", "stats", "list", "functional", "string", "dict", "convert", "random", "misc"]
    for cat in order + sorted(set(by_cat) - set(order)):
        items = by_cat.get(cat)
        if not items:
            continue
        out.append(f"### {CATEGORY_TITLES.get(cat, cat.title())}")
        out.append("")
        for b in sorted(items, key=lambda b: b.name):
            mark = " (native)" if b.name in NATIVE_BUILTINS else ""
            out.append(f"* `{b.signature}`{mark}: {b.doc}")
        out.append("")
    return "\n".join(out)


def main() -> int:
    target = ROOT / "docs" / "builtins.md"
    target.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
